apiVersion: v1
kind: Template
metadata:
  name: test-opensips-app

objects:

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: test-opensips-app
  spec:
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/jtrossbach/docker-opensips
      type: Git
    strategy:
      dockerStrategy:
        from: 
          kind: DockerImage
          name: debian:jessie
    output:
      to:
        kind: ImageStreamTag
        name: test-opensips-app:latest

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: test-opensips-app
    labels:
      applicaton: test-opensips-app
  spec:
    dockerImageRepository: ""
    tags:
      - name: latest
